### ISSUE TITLE
Create SASS For Animations

### ISSUE THREAD

**Issue by saniyusuf** [kevincobain2000/ionic-animated-modal#1]
I think it will be great if we created a SASS implementation of these animations to enable it to be easily integrated with build tools.

**Comment by kevincobain2000** [comment]
Hi! yes that'd be nice to have. I haven't played with sass much, but will start looking into it. See how it goes.

**Comment by saniyusuf** [comment]
@kevincobain2000  can you please mark this as a feature request and I can get this done in a few hours and post create pull request.
