### ISSUE TITLE
modal animations not working on device

### ISSUE THREAD

**Issue by troyshu** [kevincobain2000/ionic-animated-modal#2]
After installing as specified, the new modal animations (like "fadeIn", "bounceIn") work when serving the app locally, but don't work when testing on the device (i.e. running the built project through xcode on my iPhone), the modal just pops in with no animation. I'm also not getting any console errors in the Safari Web Inspector.

Any ideas?

**Comment by troyshu** [comment]
Nevermind, silly mistake, forgot to save the css locally. Thanks for the awesome extension!

**Comment by kevincobain2000** [comment]
Cheers thanks
