### ISSUE TITLE
How can I set the animation when modal close?

### ISSUE THREAD

**Issue by sonicwong** [kevincobain2000/ionic-animated-modal#4]
How can I set the animation when modal close?

Just like this one:
https://github.com/loringdodge/ionic-nifty-modal

**Comment by kevincobain2000** [comment]
Good Question

Edit it manually for now?

So For example, right now the **exit** animation for `bounceIn` is `bounceOut`

https://github.com/kevincobain2000/ionic-animated-modal/blob/master/www/css/style.css#L5-L8

```
<button type="" class="button" ng-click="showModal('bounceIn')">showModal bounceIn</button>
```

Just change your exit animation you like in the style file

```
.animated.modal.bounceInDown.ng-leave {
    -webkit-animation-name: slideOutLeft;//originally was bounceOutUp
    animation-name: slideOutLeft;
}
```

Hope that helps
